# CGI Test Configuration
# Usage: ./webServ resources/configFiles/cgi_test.conf
# Then open: http://localhost:8080/cgi_test.py

server
{
    listen 8080;
    root resources/sites;

    location / {
        allow_methods GET;
        index cgi_test.py;
        cgi_pass .py;
    }
}
