server
{
    listen 8080;

    root ./resources/sites/;

    location /
    {
        autoindex on;
        enable_upload on;
        upload_path ./resources/sites/cgi/uploads/;
        root ./resources/sites/;
        index __disable_index__.html;
    }

    location /here
    {
        allow_methods GET POST DELETE;
        index upload.html index.html;
	    root ./resources/sites/;

        autoindex on;
        enable_upload on;
        upload_path ./resources/sites/cgi/uploads;
    }

    location /cgi
    {
        allow_methods GET POST DELETE;
        autoindex on; 
        root ./resources/sites/cgi/;
        cgi_pass .py /usr/bin/python3;
    }

    location /cgi/uploads
    {
        allow_methods GET POST DELETE;
		root ./resources/sites/cgi/uploads/;
        enable_upload on;
        upload_path ./resources/sites/cgi/uploads/;
    }

    location /ret
    {
        return 301 here;
    }
}
