server { 
    listen 8080;
    root ./resources/sites/;                                                       
    index index.html;
    error_page 404 youpi.bad_extensionl;

	location / {
		allow_methods GET; 
		index index.html;
	}

	location /directory {
        root ./YoupiBanane;
        allow_methods GET POST;

        index youpi.bad_extension;
        cgi_pass .bla ./cgi_tester;

        client_max_body_size 100M;

        enable_upload on;
        upload_path ./YoupiBanane;
    }
    location /cgi-bin {
        root ./www/html/cgi-bin;
        allow_methods GET POST;
        cgi_pass .py /usr/bin/python3;
        client_max_body_size 10M;
    }
     location /uploads {
        root ./www/html;
        allow_methods GET POST DELETE;
        enable_upload on;
        upload_path ./www/html/uploads;
    }
    location /post_body {
        allow_methods POST;
        client_max_body_size 100;
    }
}
